[package]
authors = ["Guillem Cordoba <guillem.cordoba@gmail.com>"]
description = "A Rust client for the Holochain Conductor API"
edition = "2021"
homepage = "https://github.com/holochain/holochain-client-rust"
keywords = ["holochain", "client", "conductor-api"]
license = "MIT"
name = "holochain_client"
readme = "README.md"
repository = "https://github.com/holochain/holochain-client-rust"
resolver = "2"
version = "0.6.0-dev.5"

[workspace]
members = ["fixture/zomes/foo"]

[workspace.dependencies]
holochain_zome_types = "0.4.0-dev.14"

[dependencies]
again = "0.1"
anyhow = "1.0"
ed25519-dalek = { version = "2.1", features = ["rand_core"] }
serde = "1.0.193"
event-emitter-rs = "0.1"
rand = { version = "0.8" }
async-trait = "0.1"
parking_lot = "0.12.1"

holo_hash = { version = "0.4.0-dev.11", features = ["encoding"] }
holochain_conductor_api = "0.4.0-dev.20"
holochain_websocket = "0.4.0-dev.19"
holochain_serialized_bytes = "0.0.55"
holochain_types = "0.4.0-dev.20"
holochain_nonce = "0.4.0-dev.6"
holochain_zome_types = { workspace = true }

lair_keystore_api = { version = "0.4.5", optional = true }

tokio = { version = "1.36", features = ["rt"] }

[dev-dependencies]
arbitrary = "1.2"
holochain = { version = "0.4.0-dev.20", features = ["test_utils"] }
rand = "0.8"
kitsune_p2p_types = "0.4.0-dev.12"

[features]
default = ["lair_signing"]

lair_signing = ["dep:lair_keystore_api"]
