[package]
authors = ["Guillem Cordoba <guillem.cordoba@gmail.com>"]
description = "A Rust client for the Holochain Conductor API"
edition = "2021"
homepage = "https://github.com/holochain/holochain-client-rust"
keywords = ["holochain", "client", "conductor-api"]
license = "CAL-1.0"
name = "holochain_client"
readme = "README.md"
repository = "https://github.com/holochain/holochain-client-rust"
version = "0.2.0"

[workspace]
members = ["fixture/zomes/foo"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
again = "0.1"
anyhow = "1.0"
ed25519-dalek = "1"
holo_hash = {version = "0.0.35", features = ["encoding"]}
holochain_conductor_api = {package = "holochain_conductor_api", git = "https://github.com/holochain/holochain", rev = "c6bb672d624a884c57ffe588607ffc06aa2f7c74"}
holochain_serialized_bytes = "0.0.51"
holochain_types = {package = "holochain_types", git = "https://github.com/holochain/holochain", rev = "c6bb672d624a884c57ffe588607ffc06aa2f7c74"}
holochain_websocket = {package = "holochain_websocket", git = "https://github.com/holochain/holochain", rev = "c6bb672d624a884c57ffe588607ffc06aa2f7c74"}
holochain_zome_types = {package = "holochain_zome_types", git = "https://github.com/holochain/holochain", rev = "c6bb672d624a884c57ffe588607ffc06aa2f7c74"}
serde = "1"
url = "2.2"

[dev-dependencies]
arbitrary = "1.2"
holochain = {git = "https://github.com/holochain/holochain", rev = "c6bb672d624a884c57ffe588607ffc06aa2f7c74", features = ["test_utils"]}
rand = "0.7"
tokio = {version = "1.3", features = ["full"]}
