[package]
authors = ["Guillem Cordoba <guillem.cordoba@gmail.com>"]
description = "A Rust client for the Holochain Conductor API"
edition = "2021"
homepage = "https://github.com/holochain/holochain-client-rust"
keywords = ["holochain", "client", "conductor-api"]
license = "CAL-1.0"
name = "holochain_client"
readme = "README.md"
repository = "https://github.com/holochain/holochain-client-rust"
resolver = "2"
version = "0.4.5-rc.0"

[workspace]
members = ["fixture/zomes/foo", "utilities"]

[workspace.dependencies]
holochain_zome_types = "0.3.0-beta-dev.14"

[dependencies]
again = "0.1"
anyhow = "1.0"
ed25519-dalek = "1"
holo_hash = {version = "0.3.0-beta-dev.10", features = ["encoding"]}
holochain_conductor_api = "0.3.0-beta-dev.22"
holochain_serialized_bytes = "=0.0.53"
holochain_types = "0.3.0-beta-dev.19"
holochain_websocket = "0.3.0-beta-dev.4"
holochain_zome_types = { workspace = true }
serde = "1.0.189"
url = "2.2"

[dev-dependencies]
arbitrary = "1.2"
holochain = {version = "0.3.0-beta-dev.22", features = ["test_utils"]}
rand = "0.7"
tokio = {version = "1.3", features = ["full"]}
utilities = {path = "utilities"}
kitsune_p2p_types = "0.3.0-beta-dev.11"
