[package]
authors = ["Guillem Cordoba <guillem.cordoba@gmail.com>"]
description = "A Rust client for the Holochain Conductor API"
edition = "2021"
homepage = "https://github.com/holochain/holochain-client-rust"
keywords = ["holochain", "client", "conductor-api"]
license = "MIT"
name = "holochain_client"
readme = "README.md"
repository = "https://github.com/holochain/holochain-client-rust"
resolver = "2"
version = "0.5.0-dev.26"

[workspace]
members = ["fixture/zomes/foo", "utilities"]

[workspace.dependencies]
holochain_zome_types = "0.3.0-beta-dev.25"

[dependencies]
again = "0.1"
anyhow = "1.0"
ed25519-dalek = "1"
serde = "1.0.193"
url = "2.2"
event-emitter-rs = "0.1"
futures = "0.3"

holo_hash = { version = "0.3.0-beta-dev.20", features = ["encoding"] }
holochain_conductor_api = "0.3.0-beta-dev.34"
holochain_websocket = "0.3.0-beta-dev.11"
holochain_serialized_bytes = "0.0.53"
holochain_types = "0.3.0-beta-dev.31"
holochain_nonce = "0.3.0-beta-dev.22"
holochain_zome_types = { workspace = true }

lair_keystore_api = "0.4.0"

[dev-dependencies]
arbitrary = "1.2"
holochain = { version = "0.3.0-beta-dev.32", features = ["test_utils"] }
rand = "0.7"
tokio = { version = "1.3", features = ["full"] }
utilities = { path = "utilities" }
kitsune_p2p_types = "0.3.0-beta-dev.14"
