[package]
name = "holochain_client"
version = "0.1.0"
description = "A Rust client for the Holochain Conductor API"
authors = ["Guillem Cordoba <guillem.cordoba@gmail.com>"]
edition = "2021"
license = "CAL-1.0"
homepage = "https://github.com/holochain/holochain-client-rust"
repository = "https://github.com/holochain/holochain-client-rust"
readme = "README.md"
keywords = [ "holochain", "client", "conductor-api" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
again = "0.1"
anyhow = "1.0"
holochain_conductor_api = "0.0.53"
holochain_types = "0.0.51"
holochain_websocket = "0.0.39"
serde = "1"
url = "2.2"

[dev-dependencies]
holochain = {version = "0.0.154", features = ["test_utils"]}
tokio = {version = "1.3", features = ["full"]}
