[package]
authors = ["Holochain Foundation"]
edition = "2021"
name = "utilities"
version = "0.1.0"

[dependencies]
arbitrary = "1.2"
ed25519-dalek = "1"
holochain_client = {path = "../"}
holochain_zome_types = {workspace = true}
holochain_nonce = "0.3.0-beta-dev.18"
rand = "0.7"
