[package]
authors = ["thedavidmeister", "thedavidmeister@gmail.com"]
edition = "2021"
name = "test_wasm_foo"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "test_wasm_foo"

[dependencies]
hdi = "0.4.0-beta-dev.25"
hdk = "0.3.0-beta-dev.29"
serde = "1.0.193"
