[package]
authors = ["thedavidmeister", "thedavidmeister@gmail.com"]
edition = "2021"
name = "test_wasm_foo"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "test_wasm_foo"

[dependencies]
hdi = "0.5.1-rc.1"
hdk = "0.4.1-rc.1"
serde = "1.0.193"
