name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v19
        with:
          extra_nix_config: |
            experimental-features = flakes nix-command

      - name: Set up cachix
        uses: cachix/cachix-action@v12
        with:
          name: holochain-ci

      - name: Cache fixture
        uses: actions/cache@v3
        env:
          cache-name: fixture
        with:
          path: |
            .cargo
            fixture/zomes/foo/target
          key: ${{ matrix.os }}-build-${{ env.cache-name }}-${{ hashFiles('fixture/zomes/foo/Cargo.lock') }}

      - name: Cache client build
        uses: actions/cache@v3
        env:
          cache-name: client
        with:
          path: target
          key: ${{ matrix.os }}-cargo-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}

      - name: Build client & fixture and run tests
        run: nix develop -c $SHELL -c "cargo build && ./build-fixture.sh && cargo test"

      - name: Setup tmate session if build and test run failed
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
