name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-21.11

      - name: Set up cachix
        uses: cachix/cachix-action@v10
        with:
          name: holochain-ci

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: nix-shell --pure --run "cargo build"
      - name: Build fixture
        run: nix-shell --pure --run "./build-fixture.sh"
      - name: Run tests
        run: nix-shell --pure --run "cargo test"
