name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-22.05

      - name: Set up cachix
        uses: cachix/cachix-action@v10
        with:
          name: holochain-ci

      - name: Cache fixture
        uses: actions/cache@v3
        env:
          cache-name: cache-fixture
        with:
          path: |
            fixture
          key: ${{ matrix.os }}-build-${{ env.cache-name }}-${{ hashFiles('fixture/zomes/foo/Cargo.lock') }}

      - name: Cache client build
        uses: actions/cache@v3
        env:
          cache-name: cache-client
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.os }}-cargo-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}

      - name: Build client
        run: nix-shell --pure --run "cargo build"
      - name: Build fixture
        run: nix-shell --pure --run "./build-fixture.sh"
      - name: Run tests
        run: nix-shell --pure --run "cargo test"
